language: rust
rust:
    - stable
    - beta
    - nightly
os:
    - linux
arch:
    - amd64
    - arm64

cache: cargo

before_script:
    - rustup component add clippy
script:
    - cargo clippy -- -D warnings
    - cargo test
jobs:
    allow_failures:
        - rust: nightly

    fast_finish: true
